---
title: "ESM 239 Assignment 1"
author: "Juan Espinoza"
date: "4/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(chron)
library(dplyr)

pohnpei = read.csv("Pohnpei_FSM_TMP_PRECP.csv")
```

Precipitation 
```{r}
#plot precipitation data

prcp = ggplot(pohnpei, aes(DATE, pohnpei$PRCP))+geom_line()+ labs(y="Yearly Average Precipitation (inches)", x="Date") + theme_classic() + stat_smooth(method = "lm", col = "blue")

#Run linear regression for precipitation data

prcp_slp = lm(PRCP~DATE, data = pohnpei)
summary(prcp_slp)

#Value of the slope is -0.17 inches/year; however, this is not statistically significant. p-value = 0.2482

#Run statistical testing

t.test(subset(pohnpei$PRCP, pohnpei$DATE %in% 1952:1985), subset(pohnpei$PRCP, pohnpei$DATE %in% 1986:2019))

#There is not a significant difference in means p-value = 0.4027

#Calculate return period for rainfall > 200 inches 

prcp_high = ifelse(pohnpei$PRCP >= 200, 1, 0)

#Test Juan
```

Temperature
```{r}
#Started by plotting the average temperature for the entire time period

pohnpei_tavg_yearly_plot <-ggplot(pohnpei, aes(x = DATE, y = TAVG)) +
  geom_point(color = "#5792CC") +
  theme_classic() +
  ggtitle("Pohnpei Average Temperatures (1952 - 2019)") +
  xlab("Year") +
  ylab("Average Daily Minimum Temperature (°F)") +
  scale_x_continuous(limits = c(1970, 2018)) +
  geom_smooth(method = "lm", col = "#5792CC") +
  theme(plot.title = element_text(size=12)) +
  scale_y_continuous()

pohnpei_tavg_yearly_plot

#Summarize data for average for TMIN and TMAX

clim.mwy = pohnpei %>% group_by(DATE) %>% summarize(tmax=mean(TMAX), tmin=mean(TMIN))

#Plot TMIN and TMAX with trend lines
pohnpei_min_max = ggplot(clim.mwy, aes(x=DATE, tmax))+geom_point(col="red")+
  scale_y_continuous(limits=c(min(clim.mwy$tmin), max(clim.mwy$tmax)))+
geom_point(data=clim.mwy, aes(x=DATE, tmin), col="blue")

pohnpei_min_max =pohnpei_min_max+stat_smooth (method="lm", col="red")

pohnpei_min_max

pohnpei_min_max+ stat_smooth(data=clim.mwy, aes(x=DATE,tmin), col="blue", method="lm")

#close up of tmin
ggplot(clim.mwy, aes(x=DATE, y=tmin)) + stat_summary(fun.y="mean", geom="point", col="red", size=4)+theme(axis.text=element_text(size=14, face="bold"), axis.title=element_text(size=14, face="bold")) + geom_smooth(method="lm")

#close up of tmax
ggplot(clim.mwy, aes(x=DATE, y=tmax)) + stat_summary(fun.y="mean", geom="point", col="red", size=4)+theme(axis.text=element_text(size=14, face="bold"), axis.title=element_text(size=14, face="bold")) + geom_smooth(method="lm")
```

Temperature STAT
```{r}
#linear regression on min max
res_min=lm(tmin~DATE, data=clim.mwy)

summary(res_min)

#Multiple R-squared = 0.02968, Adjusted R-squared = 0.01498, F-Statistic = 2.019 on 1 and 66 DF, p-value = 0.1601

confint(res_min, "DATE", level=0.95)

#2.5% = -0.003729429
#97.5% = 0.02213612
res_max=lm(tmax~DATE, data=clim.mwy)

summary(res_max)

#Multiple R-squared = 0.4257, Adjusted R-squared = 0.417, F-statistic = 48.92 on 1 and 66 DF, p-value = 1.6610e-09

confint(res_max, "DATE", level=0.95)

# 2.5% = 0.0172953
#97.5% = 0.03111489

#t.test for average, min, and max temperature

t.test(subset(pohnpei$TAVG, pohnpei$DATE %in% 1952:1985), subset(pohnpei$TAVG, pohnpei$DATE %in% 1986:2019))

#Average temp: t = -2.3249, df = 64.092, = p-value = 0.02326

t.test(subset(clim.mwy$tmin, clim.mwy$DATE %in% 1952:1985), subset(clim.mwy$tmin, clim.mwy$DATE %in% 1986:2019))

#Min temp: t = 0.27361, df = 44.9363, p-value = 0.7856

t.test(subset(clim.mwy$tmax, pohnpei$DATE %in% 1952:1985), subset(clim.mwy$tmax, clim.mwy$DATE %in% 1986:2019))

#Max temp: t = -5.2845, df = 56.792, p-value = 2.079e-06
```

